sudo: required
language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm run initial
branches:
  only:
  - develop
before_script:
- npm run build
script:
- karma start karma.conf.js --single-run
after_success:
- git config user.name "Travis CI"
- git config user.email "$COMMIT_AUTHOR_EMAIL"
- git checkout release
- git add . dist/*
- git commit -m "Release version $(cat package.json | grep version | awk -F\":\" '{print $2}' | sed 's/[\", ]//g')#$TRAVIS_BUILD_NUMBER"
- git push -q https://$access_token@github.com/Developers-SP/my-team-web.git release


