sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
branches:
  only:
  - develop
before_script:
  - npm run initial
script:
  - npm test
