# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
machine:
jobs:
  build:
    docker:
      - image: circleci/node:9.3
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-

      - run:
          name: Install dependecies
          command: npm i --silent

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Make build
          command: npm run build

      - run:
          name: Run tests
          command: karma start karma.conf.js --single-run
